import Item from './classes/item.js'

const firstLocation = [
    { },
    { },
    { },
    { },
    { },
    { },
    { },
    { },
    { },
    { },
    { },
    { },
    { items: [new Item("item1", 'images/catcher3.gif')] },
    { },
    { },
    { },
    { },
    { },
    { },
    { },
    { },
    { },
    { },
    { },
    { transition: ["to second location", "second location", "images/gamer.gif"] }
]
const secondLocation = [
    { },
    { },
    { },
    { },
    { },
    { },
    { },
    { },
    { },
    { },
    { },
    { },
    { },
    { },
    { },
    { },
    { },
    { },
    { },
    { },
    { },
    { },
    { },
    { },
    { transition: ["to first location", "берег реки", "images/gamer.gif"]},
]

export const locations = new Map([ ["берег реки", firstLocation], ["second location", secondLocation] ])
export const startLocation = "берег реки"